/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Task Status
     * @description Latest event of a task, so a reloaded page can resume following it.
     */
    get: operations["task_status_api_tasks__task_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_api_tasks__task_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Task */
    post: operations["create_task_api_tasks_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Docs */
    get: operations["list_docs_api_docs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docs/{doc_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Document */
    get: operations["document_api_docs__doc_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docs/{doc_id}/flow": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Flow */
    get: operations["flow_api_docs__doc_id__flow_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docs/{doc_id}/sentences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sentences */
    get: operations["sentences_api_docs__doc_id__sentences_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docs/{doc_id}/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Suggestions */
    get: operations["suggestions_api_docs__doc_id__suggestions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docs/{doc_id}/source": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Source */
    get: operations["source_api_docs__doc_id__source_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docs/{doc_id}/assets/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Asset */
    get: operations["asset_api_docs__doc_id__assets__name__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docs/{doc_id}/steps/{step_id}/explanation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Explanation */
    post: operations["explanation_api_docs__doc_id__steps__step_id__explanation_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Document */
    Document: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "pdf" | "html";
      /** Source Url */
      source_url?: string | null;
      /** Sections */
      sections?: components["schemas"]["Section"][];
      /** Paragraphs */
      paragraphs?: components["schemas"]["Paragraph"][];
      /** Sentences */
      sentences?: components["schemas"]["Sentence"][];
      /** Pages */
      pages?: [number, number][];
      /** Warnings */
      warnings?: string[];
    };
    /** Explanation */
    Explanation: {
      /** Explanation */
      explanation: string;
      /** Anchors */
      anchors: string[];
    };
    /** Flow */
    Flow: {
      /** Steps */
      steps: components["schemas"]["Step"][];
      /** Links */
      links: components["schemas"]["Link"][];
      /** Terms */
      terms?: components["schemas"]["TermCard"][];
      /**
       * Genre
       * @default scientific
       */
      genre: string;
      /**
       * Thesis
       * @default
       */
      thesis: string;
      metadata: components["schemas"]["Metadata"];
      /** Patterns */
      patterns?: components["schemas"]["Pattern"][];
      generation: components["schemas"]["Generation"];
    };
    /** Generation */
    Generation: {
      /**
       * Language
       * @default auto
       */
      language: string;
      /** Model */
      model: string;
      /** Timestamp */
      timestamp: string;
      /**
       * Prompt Version
       * @default 2.1
       */
      prompt_version: string;
      /**
       * Total Tokens
       * @default 0
       */
      total_tokens: number;
      /** Estimated Cost Usd */
      estimated_cost_usd?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Link */
    Link: {
      /** Id */
      id: string;
      /** Src */
      src: string;
      /** Dst */
      dst: string;
      /**
       * Type
       * @enum {string}
       */
      type: "support" | "cause" | "refine" | "contradict";
      /**
       * Connective
       * @default
       */
      connective: string;
      /** Anchors */
      anchors: string[];
      /**
       * Confidence
       * @default 0.5
       */
      confidence: number;
      /**
       * Status
       * @default to_verify
       * @enum {string}
       */
      status: "verified" | "partial" | "to_verify";
    };
    /** Metadata */
    Metadata: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "pdf" | "html";
      /** Source Url */
      source_url?: string | null;
      /** Created At */
      created_at: string;
      /**
       * Demo
       * @default false
       */
      demo: boolean;
      /** Language */
      language?: string | null;
    };
    /** Paragraph */
    Paragraph: {
      /** Id */
      id: string;
      /** Text */
      text: string;
      /** Section Id */
      section_id: string;
      /** Page */
      page?: number | null;
      /** Words */
      words?: components["schemas"]["Word"][];
      /** Dom Id */
      dom_id?: string | null;
      /** Latex */
      latex?: string[];
    };
    /** Pattern */
    Pattern: {
      /**
       * Type
       * @enum {string}
       */
      type:
        | "divergence"
        | "convergence"
        | "contradiction"
        | "refinement"
        | "causality";
      /** Step Ids */
      step_ids: string[];
    };
    /** Section */
    Section: {
      /** Id */
      id: string;
      /** Title */
      title: string;
    };
    /** Sentence */
    Sentence: {
      /** Id */
      id: string;
      /** Text */
      text: string;
      /** Section Id */
      section_id: string;
      /** Order */
      order: number;
      /** Page */
      page?: number | null;
      /** Bbox */
      bbox?: [number, number, number, number][];
      /** Dom Id */
      dom_id?: string | null;
      /** Paragraph Id */
      paragraph_id: string;
    };
    /** Step */
    Step: {
      /** Id */
      id: string;
      /** Parent */
      parent?: string | null;
      /**
       * Type
       * @enum {string}
       */
      type:
        | "question"
        | "premise"
        | "claim"
        | "evidence"
        | "objection"
        | "conclusion";
      /** Label */
      label: string;
      /** Summary */
      summary: string;
      /** Anchors */
      anchors: string[];
      /** Quote */
      quote: string;
      /**
       * Confidence
       * @default 0.5
       */
      confidence: number;
      /**
       * Status
       * @default to_verify
       * @enum {string}
       */
      status: "verified" | "partial" | "to_verify";
      /**
       * First Position
       * @default 0
       */
      first_position: number;
    };
    /** Suggestion */
    Suggestion: {
      /**
       * Target Type
       * @enum {string}
       */
      target_type: "step" | "link";
      /** Target Id */
      target_id: string;
      /** Category */
      category: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "info" | "warning" | "critical";
      /** Message */
      message: string;
      /** Suggested Rewrite */
      suggested_rewrite?: string | null;
      /** Anchors */
      anchors: string[];
      /**
       * Source
       * @enum {string}
       */
      source: "rule" | "llm";
    };
    /** TaskAccepted */
    TaskAccepted: {
      /** Task Id */
      task_id?: string | null;
      /** Doc Id */
      doc_id?: string | null;
    };
    /** TermCard */
    TermCard: {
      /** Term */
      term: string;
      /** Definition */
      definition: string;
      /** Anchors */
      anchors: string[];
      /** Step Ids */
      step_ids: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** Word */
    Word: {
      /** Text */
      text: string;
      /** Start */
      start: number;
      /** End */
      end: number;
      /** Bbox */
      bbox: [number, number, number, number];
      /** Page */
      page?: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  task_status_api_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  events_api_tasks__task_id__events_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_task_api_tasks_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskAccepted"];
        };
      };
    };
  };
  list_docs_api_docs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Metadata"][];
        };
      };
    };
  };
  document_api_docs__doc_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        doc_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Document"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  flow_api_docs__doc_id__flow_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        doc_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Flow"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sentences_api_docs__doc_id__sentences_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        doc_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Sentence"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  suggestions_api_docs__doc_id__suggestions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        doc_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Suggestion"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  source_api_docs__doc_id__source_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        doc_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  asset_api_docs__doc_id__assets__name__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        doc_id: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  explanation_api_docs__doc_id__steps__step_id__explanation_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        doc_id: string;
        step_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Explanation"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
